id: 79da0be579f04c41b1da8bb6dbe6d904
initial_creation_type: ocr
source_metadata:
  volumes:
    4611ff7c07184421853de2ce4c47d3ac:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: ལས་ཀྱི་སྒྲིབ་པ་རྣམ་པར་སྦྱོང་བའི་ཆོ་ག་བཤད་པ།
      total_pages: 1529
      volume_number: 67
